on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Get RSS Feed
      uses: ./
      with:
        feed_url: https://blog.rongying.co/feed.xml
        count: 3
        readme_path: 'tests/readme.test.md'
    - name: Commit file changes
      run: |
          git config --global user.name 'kohrongying'
          git config --global user.email 'kohrongying@gmail.com'
          git add .
          git commit -m "Update README"    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
